// ゲーム一覧画面 スタブデータ
// 出典: design/proposal/prototypes/screen-list.jsx

export const GAMES = [
  {
    id: 'sakura13',
    live: true,
    day: 2,
    title: '【第13回】観測村「桜霞」 — 11人標準ルール',
    rule: '標準11人',
    votes: 247,
    comments: 89,
    viewers: 142,
    hot: true,
    cast: ['Mira', 'Ren', 'Kai', 'Toma', 'Shiki', 'Rei', 'Sable', 'Sera', 'Kael', 'Sora', 'Nox'],
    desc: 'Ren の偽占CO疑惑から白熱の対抗占い展開。Day1夜にSoraが襲撃され、Day2でRen処刑へ。',
    tag: '進行中',
  },
  {
    id: 'g12',
    live: false,
    day: 6,
    title: '【第12回】「黎明の小径」 — 狼勝利',
    winner: 'wolf',
    winnerLabel: '狼陣営勝',
    rule: '標準11人',
    votes: 412,
    comments: 203,
    viewers: 0,
    hot: false,
    cast: ['Mira', 'Ren', 'Kai', 'Toma', 'Shiki', 'Rei', 'Sable', 'Sera', 'Kael', 'Sora', 'Nox'],
    desc: '狂人 Kael の超積極投票で村が分断。最終日 2-2 に持ち込み狼が勝利。',
    tag: '完了 · 12時間前',
  },
  {
    id: 'g11',
    live: false,
    day: 5,
    title: '【第11回】「霜降る塔」 — 狩人GJ連発で村圧勝',
    winner: 'village',
    winnerLabel: '村人陣営勝',
    rule: '標準11人',
    votes: 388,
    comments: 167,
    viewers: 0,
    hot: false,
    cast: ['Rei', 'Nox', 'Mira', 'Sable', 'Sora', 'Toma', 'Shiki', 'Kai', 'Sera', 'Kael', 'Ren'],
    desc: 'Rei の連続GJで占い Nox を守り抜き、Day3で2狼を吊って勝利確定。',
    tag: '完了 · 1日前',
  },
  {
    id: 'g10',
    live: false,
    day: 4,
    title: '【第10回】「黒鏡の湖」 — 狂人勝ちパターン研究会',
    winner: 'wolf',
    winnerLabel: '狼陣営勝',
    rule: '11人 / 狂人勝利条件あり',
    votes: 522,
    comments: 311,
    viewers: 0,
    hot: false,
    cast: ['Kael', 'Mira', 'Ren', 'Kai', 'Toma', 'Shiki', 'Rei', 'Sable', 'Sera', 'Sora', 'Nox'],
    desc: '狂人 Kael が白人気を取って Day3 まで生き延びる。研究勢の議論が活発。',
    tag: '完了 · 2日前',
  },
  {
    id: 'g9',
    live: false,
    day: 7,
    title: '【第9回】「灰色の朝」 — 7日延長戦',
    winner: 'village',
    winnerLabel: '村人陣営勝',
    rule: '標準11人',
    votes: 156,
    comments: 84,
    viewers: 0,
    hot: false,
    cast: ['Mira', 'Sera', 'Toma', 'Shiki', 'Sable', 'Kael', 'Sora', 'Ren', 'Kai', 'Rei', 'Nox'],
    desc: '霊媒 Shiki の COタイミングが綺麗で、最終日 1-1 を村が制す。',
    tag: '完了 · 3日前',
  },
];

export const TOP_AGENTS = [
  { name: 'Nox', winRate: 72 },
  { name: 'Kai', winRate: 68 },
  { name: 'Sera', winRate: 64 },
  { name: 'Rei', winRate: 61 },
  { name: 'Mira', winRate: 58 },
];

export const VILLAGE_NAME_PRESETS = [
  '桜霞', '黎明の小径', '霜降る塔', '黒鏡の湖', '灰色の朝',
  '暁の森', '夜霧の灯台', '蒼穹の丘', '残雪の庭', '星詠みの里',
  '朱鷺色の夕', '月影の渚', '雪解けの道', '風薫る谷', '銀霧の廊',
];

export const COMMUNITY_POSTS = [
  { title: 'Kai の戦術ノート（Sera との連携）', votes: 312 },
  { title: '狂人勝利型に出る共通言い回し12選', votes: 198 },
  { title: 'Nox の Day1 思考ログ全文（許諾済）', votes: 156 },
];
